version: '3.7'

services:
  gallery:
    build: .
    ports:
      - '3061:3061'
    depends_on:
      - 'mysql'
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: student
      MYSQL_DB: couchbnb
    command: sh -c 'npm run seed'
    command: sh -c 'npm run startd'



  mysql:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: student
